Hsinha11/Leetcode-solutions

968-binary-tree-cameras/README.md
968-binary-tree-cameras/binary-tree-cameras.py

Used the dfs approach as mentioned earlier

Added the solution for the Binary Tree Cameras problem

---

3300-minimum-element-after-replacement-with-digit-sum/README.md
3300-minimum-element-after-replacement-with-digit-sum/minimum-element-after-replacement-with-digit-sum.py

[https://leetcode.com/problems/minimum-element-after-replacement-with-digit-sum/solutions/5844941/easiest-faster-lesser-c-python3-java-c-python-c-explained-beats-100/]

Added the solution for minimum-element-after-replacement-with-digit-sum 

---

301-Remove-Invalid-Parentheses/README.md
301-Remove-Invalid-Parentheses/remove-invalid-parentheses.py

Solved the problem using the approach mentioned earlier.

301. Remove Invalid Parentheses

---

188-best-time-to-buy-and-sell-stock-iv/188-best-time-to-buy-and-sell-stock-iv.cpp
188-best-time-to-buy-and-sell-stock-iv/README.md

Completed the implementation of assigned issue for '188-best-time-to-buy-and-sell-stock-iv' using dynamic programming approach in C++ .
Have added a readme file with examples and explaination of the approach.
Thank You

188-best-time-to-buy-and-sell-stock-iv

---

410-split-array-largest-sum/README.md
410-split-array-largest-sum/Split-array-largest-sum.cpp

Completed the implementation of assigned issue for '410. Split Array Largest Sum' using binary search approach in C++ .
Have added a readme file with examples and explaination of the approach.
please merge my pull request under appropriate hacktoberfest 2024 tags
Thank You

410. Split Array Largest Sum

---

-410-split-array-largest-sum/-410-split-array-largest-sum.cpp
-410-split-array-largest-sum/readme.md

Added Split array largest sum

---

131-Palindrome-Partitioning/README.md
131-Palindrome-Partitioning/palindromeparitioning.py

I have given the pr for Palindrome Partitioning in python
please merge it into the repo

131. Palindrome Partitioning

---

44-Wildcard-Matching/44-Wildcard-Matching.cpp
44-Wildcard-Matching/Readme.md
README.md
Readme.md

I have updated the readme file and added a cpp solution to the problem Wildcard Matching on leetcode

44 -Wildcard-Matching And Updated the readme according to the need

---

229-majority-element-ii/majority-element-ii.cpp

the old code used an hash map which introduced an linear space complexity , the provided cpp solution uses linear time complexity and constant space complexity as requested in followup of readme.md file please considering merging my code under hacktoberfest tag

added optimal cpp code for problem 229-majority-element-ii

---

1106. Parsing A Boolean Expression/README.md
1106. Parsing A Boolean Expression/parsing-a-boolean-expression.py

Completed the implementation of the problem "1106. Parsing A Boolean Expression] Leetcode using python.
Also Added the README.md file which consists of the Problem Statement, Examples .
Kindly merge my Pull Request with the appropriate Hacktoberfest 2024 Tags!
Cheers

1106. Parsing A Boolean Expression

---

2938. Separate Black and White Balls/README.md
2938. Separate Black and White Balls/solution.cpp

The problem involves rearranging a binary string representing black and white balls, where 1 denotes a black ball and 0 denotes a white ball. The goal is to determine the minimum number of adjacent swaps needed to group all black balls to the right and all white balls to the left. The approach involves iterating through the string from right to left, counting the number of white balls encountered. For each black ball found, the current count of white balls is added to the total swaps needed, as each white ball requires a swap to allow the black ball to move to its correct position. This efficient method ensures a time complexity of O(n)O(n).

2938. Separate Black and White Balls

---

632. Smallest Range Covering Elements from K Lists/README.md
632. Smallest Range Covering Elements from K Lists/smallest-range-covering-elements-from-k-lists.py

Completed the implementation of the problem "632. Smallest Range Covering Elements from K Lists" Leetcode using python.
Also Added the README.md file which consists of the Problem Statement, Examples .
Kindly merge my Pull Request with the appropriate Hacktoberfest 2024 Tags!
Cheers

632. Smallest Range Covering Elements from K Lists

---

1823-find-the-winner-of-circular-game/README.md
1823-find-the-winner-of-circular-game/find-winner-of-circular-game.cpp

Implemented the Josephus Problem solution using an optimized approach. The solution simulates the elimination process in a circle where every k-th person is removed until only one remains. The algorithm handles both small and large inputs efficiently. The README is updated with a problem description and usage instructions for clarity.

Added problem 1823: Finding winner of the circular game.

---

678-valid-parenthesis-string/README.md
678-valid-parenthesis-string/valid-parenthesis-string.cpp
678-valid-parenthesis-string/valid-parenthesis-string.py

Pull Request for issue #40 
The pull request contains:
- README.md - contains the questions and explanation of the solution
- valid-parenthesis-string.py - Python solution for the question
- valid-parenthesis-string.cpp - C++ solution for the question
The code solutions are aimed for leetcode, and hence do not contain the required header files.

678. Valid Parenthesis String Solution

---

641-design-circular-deque/README.md
641-design-circular-deque/design-circular-deque.cpp

Completed the implementation of the problem "641. Design circular deque" Leetcode using c++.
Also Added the README.md file which consists of the Problem Statement, Examples .
Kindly merge my Pull Request with the appropriate Hacktoberfest 2024 Tags!
Cheers

Problem "641. Design circular deque"

---

1493. Longest Subarray of 1's After Deleting One Element/README.md
1493. Longest Subarray of 1's After Deleting One Element/longest-subarray-of-1s-after-deleting-one -element.py

Completed the implementation of the problem "1493. Longest Subarray of 1's After Deleting One Element" Leetcode using python.
Also Added the README.md file which consists of the Problem Statement, Examples .
Kindly merge my Pull Request with the appropriate Hacktoberfest 2024 Tags!
Cheers

1493. Longest Subarray of 1's After Deleting One Element

---

2530. Maximal Score After Applying K Operations/README.md
2530. Maximal Score After Applying K Operations/Solution.cpp

2530. Maximal Score After Applying K Operations 

---

463-islandparameter.cpp

question :- You are given row x col grid representing a map where grid[i][j] = 1 represents land and grid[i][j] = 0 represents water.
Grid cells are connected horizontally/vertically (not diagonally). The grid is completely surrounded by water, and there is exactly one island (i.e., one or more connected land cells).
The island doesn't have "lakes", meaning the water inside isn't connected to the water around the island. One cell is a square with side length 1. The grid is rectangular, width and height don't exceed 100. Determine the perimeter of the island.

463- island parameter

---

6.Zigzag-Conversion/readme.md
6.Zigzag-Conversion/zigzag-conversion.py

This pull request implements the solution for the Zigzag Conversion problem as described in LeetCode.
Problem Statement:
Given a string and a number of rows (numRows), the string is written in a zigzag pattern across multiple rows and then read row-by-row.
Example:
Input: "PAYPALISHIRING", numRows = 3
Output: "PAHNAPLSIIGYIR"
Approach:
The solution simulates the zigzag pattern by iterating through the string and placing characters into the corresponding rows in a zigzag order.
The characters are then read row-by-row to construct the final string.
Edge Cases Considered:
If numRows is 1, the original string is returned since no zigzag conversion is needed.
The algorithm handles strings shorter than or equal to numRows.

6. ZigZag Conversion

---

31-Next-Permutation/ReadMe.md
31-Next-Permutation/next-permutation.py

This PR resolves issue https://github.com/Hsinha11/Leetcode-solutions/issues/56

31. Next Permutation

---

151-reverse-words-in-a-string/README.md
151-reverse-words-in-a-string/reverse-words-in-a-string.py

Added 151 Reverse words in a string leetcode problem with README.md and python file.
Kindly merge my pull request with the appropriate Hacktoberfest 2024 tags!

151 Reverse words in a string

---

0001-Two-Sum/readme.md
0001-Two-Sum/two-sum.py

I have added two-sum.py which has the solution to the problem and readme.md which has the description of the problem.

Added solution to 0001-Two-Sum

---

80-remove-duplicates-from-sorted-array-ii/README.md
80-remove-duplicates-from-sorted-array-ii/remove-duplicates-from-sorted-array-ii.py

Completed the implementation of the problem 80. Remove Duplicates from Sorted Array II" using python
Also Added README.md file which consists of the Problem Statement and approach.
Please merge my Pull Request with the appropriate Hacktoberfest 2024 Tags
Thank You

80. Remove Duplicates from Sorted Array II

---

46-Permutations/46-Permutations.py
46-Permutations/README.md

Solution added for the problem mentioned in the #76 issue.

46. Permutations

---

540. Single Element in a Sorted Array/single element in a sorted array.cpp

You are given a sorted array consisting of only integers where every element appears exactly twice, except for one element which appears exactly once.
Return the single element that appears only once.
Your solution must run in O(log n) time and O(1) space.

single element in a sorted array

---

48-rotate-image/48-rotate-image.java
48-rotate-image/README.md

`Solution` class is designed to rotate a given `n x n` matrix by 90 degrees in a clockwise direction. The implementation consists of two primary methods: `swap` and `rotate`. Below is a detailed explanation of how these methods work and the overall flow of the code.
---
- **Class Name**: `Solution`
- **Purpose**: To provide a method for rotating a square matrix (2D array) by 90 degrees clockwise.
- **Purpose**: This method reverses the order of the rows in the input matrix.
- **Parameters**:
- `matrix`: A 2D array representing the matrix to be manipulated.
- **Functionality**:
- The method first retrieves the number of rows in the matrix.
- It then iterates through the first half of the rows (`i < rows / 2`). For each iteration:
- It temporarily stores the current row in a variable …

Created 48-rotate-image.java

---

Move_all_zeros_to_end/README.md
Move_all_zeros_to_end/moveAllZeorosToEnd.cpp

283.Move all zeros to end

---

485. MaxconsecutiveOnes/485. maxconsecutiveones.cpp
485. MaxconsecutiveOnes/readme-maxconsecutiveones.md

added the solution and readme file for the same. 
Please add the hacktoberfest tags for the PR.

485. Max Consecutive Ones

---

1752. Check if Array is Sorted and Rotated/1752. sortedarray.cpp
1752. Check if Array is Sorted and Rotated/readme-sortedarray.md

added solution and readme file for the same.

1752. Check if Array is Sorted and Rotated

---

valid_palindrome/readme_validpalindrome.md
valid_palindrome/valid_palindrome.cpp

can you please add hacktoberfest label

125.Valid palindrome-solved

---

74.2D_array_search/readme_2darray.md

74. Search a 2D matrix

---

Remove Duplicates from Sorted List II/README.md
Remove Duplicates from Sorted List II/Remove Duplicates from Sorted List II.cpp

I have added the solution for the Question no. 82 in top 150 interview questions.

Time:  0 ms (100%) | Memory: 15.51 MB(48.45%) -LeetSync

---

81-Search-In-Rotated-Sorted-Array-II/README.md
81-Search-In-Rotated-Sorted-Array-II/rotated-sorted-array.cpp

Time: 0 ms (100%) | Memory: 16.94 MB (26.63%)  - LeetSync

---

1695-Maximun-Erasure-Vlue/MaxErasureValue.java
1695-Maximun-Erasure-Vlue/Readme.md

You are given an array of positive integers nums and want to erase a subarray containing unique elements. The score you get by erasing the subarray is equal to the sum of its elements.
Return the maximum score you can get by erasing exactly one subarray.

added leetcode ques no 1695

---

1739-Building-Boxes/Building-Boxes.py
1739-Building-Boxes/README.MD

Building Boxes code leetcode question using math

Building Boxes code leetcode

---

1895-minimum-number-of-operations-to-move-all-balls-to-each-box/README.md
1895-minimum-number-of-operations-to-move-all-balls-to-each-box/minimum-number-of-operations-to-move-all-balls-to-each-box.py

Add Python solution and README approach for 1895
- **Summary**: Add Python solution for 1895 “Minimum Number of Operations to Move All Balls to Each Box” and update README with approach/complexity.
- **Changes**:
- `minimum-number-of-operations-to-move-all-balls-to-each-box.py` (O(n) two-pass)
- `README.md` (Approach, Complexity, reference code)
- **Approach**: Two passes (left→right, right→left) accumulating move costs; sum per index.
- **Complexity**: Time O(n); Space O(n) result, O(1) extra.
- **Validation**: "110" → [1,1,3]; "001011" → [11,8,5,4,3,4]

Add Python solution for 1895 using O(n) two-pass approach

---

3-Longest-Substring-Without-Repeating-Characters/README.md
3-Longest-Substring-Without-Repeating-Characters/Solution.cpp
3-Longest-Substring-Without-Repeating-Characters/Solution.java

- Implemented optimized sliding window approach with hash set
- Added C++ and Java solutions with example usage
- Documented problem in README.md including:
• Problem statement and examples with explanations
• Constraints and edge cases
• Step-by-step approach with time & space complexity
• Reference C++ and Java implementations

Add solution for Leetcode Problem "3. Longest Substring Without Repeating Characters"

---

1906_Minimum_Absolute_Difference_Queries/1906_Minimum_Absolute_Difference_Queries.java
1906_Minimum_Absolute_Difference_Queries/README.md

Solution and a brief explanation for the problem 1906. Minimum Absolute Difference Queries. The solution is in Java with proper comments for code readability.

Add Solution for LC:1906

---

1021-distribute-coins-in-binary-tree/README.md
1021-distribute-coins-in-binary-tree/distribute-coins-in-binary-tree.py
123-best-time-to-buy-and-sell-stock-iii/README.md
123-best-time-to-buy-and-sell-stock-iii/best-time-to-buy-and-sell-stock-iii.py

Add Python solution and README approach for 123
- **Summary**: Add Python solution for 123 “Best Time to Buy and Sell Stock III” and update README.
- **Changes**:
- `best-time-to-buy-and-sell-stock-iii.py` (two-transaction state machine)
- `README.md` (Approach, Complexity, Python reference)
- **Approach**: Track `buy1`, `profit1`, `buy2`, `profit2`. Update per price:
- `buy1 = min(buy1, price)`, `profit1 = max(profit1, price - buy1)`
- `buy2 = min(buy2, price - profit1)`, `profit2 = max(profit2, price - buy2)`
- **Complexity**: Time O(n); Space O(1).

Add Python solution and approach for 123 Best Time to Buy and Sell Stock III

---

1021-distribute-coins-in-binary-tree/README.md
1021-distribute-coins-in-binary-tree/distribute-coins-in-binary-tree.py

- **Summary**: Add Python solution for 1021 “Distribute Coins in Binary Tree” and update README.
- **Changes**:
- `distribute-coins-in-binary-tree.py` (postorder DFS with subtree balance)
- `README.md` (Approach, Complexity, Python reference)
- **Approach**: Postorder DFS; each node returns `balance = node.val + left + right - 1`. Moves += `abs(left) + abs(right)`.
- **Complexity**: Time O(n); Space O(h) recursion stack.

Add Python solution and README approach for 1021

---

1468-check-if-n-and-its-double-exist/README.md
1468-check-if-n-and-its-double-exist/check-if-n-and-its-double-exist.cpp
1468-check-if-n-and-its-double-exist/check-if-n-and-its-double-exist.py

- Add `check-if-n-and-its-double-exist.py` (O(n) set-based).
- Update `README.md` with approach and complexity.
- Add brief approach comment in C++ file.
Approach: Track seen values; for each x, check `2*x` or (x even and `x//2`) in seen.
Complexity: Time O(n), Space O(n).

Add Python solution for 1468 and document approach & complexity

---

2528-Maximize-the-Minimum-Powered-City/2528-Maximize-the-Minimum-Powered-City.py
2528-Maximize-the-Minimum-Powered-City/README.md

Maximum the minimum powered city

Maximum the minimum powered city 

---

407_Trapping_Rain_Water_II/407.Trapping_Rain_Water_II.py
407_Trapping_Rain_Water_II/README.md

**Summary:**  
Add Python solution for 407 “Trapping Rain Water II” and update README.
**Changes:**  
- Created `Trapping_rain_water_II.py` file  
- Updated `README.md` with approach
**Approach:**  
We start from the **boundary cells (walls)** and use a **min-heap** to always process the **lowest wall first**. For each cell, we check its neighbors: if a neighbor is lower, water is trapped equal to `boundary_height - neighbor_height`, then we push the neighbor with height = `max(neighbor_height, boundary_height)`. Repeat until all cells are visited.
**Complexity:**  
- **Time:** O(m * n * log(m * n))  
- **Space:** O(m * n)

Added Python Solution for trapping rain water II

---

322_Coin_Change/322_Coin_Change.cpp
322_Coin_Change/322_Coin_Change.java
322_Coin_Change/README.md

This pull request adds the solution for LeetCode Problem 322: Coin Change.  
The implementations are provided in both C++ and Java.  
Problem highlights:
- Difficulty: Medium  
- Topic: Dynamic Programming  
- Approach: Bottom-up DP using a 1D array to store the minimum number of coins required for each amount.
Key details:
- Added C++ solution file: 322_Coin_Change.cpp
- Added Java solution file: 322_Coin_Change.java
- Updated README with problem statement, approach, examples, and folder structure.
This contribution follows the repository guidelines:
- Used correct problem numbering and naming convention
- Provided explanation and optimized solutions
- Verified correctness with sample test cases
Requesting review and merge with hacktoberfest2025 , hacktoberfest-accepted tag.

Add solution for LeetCode 322 Coin Change in C++ and Java

---

-787-Cheapest Flights Within K Stops/Code.cpp
-787-Cheapest Flights Within K Stops/Code.java
-787-Cheapest Flights Within K Stops/Code.py
-787-Cheapest Flights Within K Stops/Readme.md

This PR adds solutions for the LeetCode problem **"Cheapest Flights Within K Stops"** implemented in **C++**, **Java**, and **Python**.  
The problem aims to find the cheapest flight cost from a source city to a destination city with at most `k` stops using a BFS-based shortest path algorithm.
- **Code.cpp** – C++ implementation  
- **Code.java** – Java implementation  
- **Code.py** – Python implementation  
- **Readme.md** – Problem statement, constraints, and detailed approach  
We use a **BFS-based shortest path algorithm** (similar to Bellman-Ford) to find the cheapest price from `src` to `dst` with at most `k` stops.  
1. Build an adjacency list from the `flights` array where each entry stores `(destination, cost)`.  
2. Use a queue to perform **level-order traversal**, where each …

Added Solution for "Cheapest Flights Within K Stops" (LeetCode #787)

---

-51-N_Queens/Code.cpp
-51-N_Queens/Code.java
-51-N_Queens/Code.py
-51-N_Queens/Readme.md

This PR adds the **N-Queens** problem solution to the DSA repository.  
It includes complete implementations in **C++**, **Java**, and **Python**, along with a detailed **README.md** explaining the problem, approach, and complexity analysis.
- **Problem Link:** [https://leetcode.com/problems/n-queens/](https://leetcode.com/problems/n-queens/)
- **Approach:** Backtracking algorithm to explore all valid configurations where no two queens attack each other.
- **Files Added:**
- `Code.cpp`
- `Code.java`
- `Code.py`
- `README.md`
- **Time Complexity:** O(N!)
- **Space Complexity:** O(N²)
Added a well-documented and optimized solution for the classic N-Queens problem, demonstrating recursive backtracking and clean modular design.

Added N-Queens Problem Solution (LeetCode 51)

---

1903-largest-odd-number-in-string/README.md
1903-largest-odd-number-in-string/largest-odd-number.cpp

Added solution and documentation for LeetCode problem #1903 - Largest Odd Number in String.
- Language: C++
- Time Complexity: O(n)
- Space Complexity: O(1)
- `1903-largest-odd-number-in-string/largest-odd-number.cpp`: Implementation
- `1903-largest-odd-number-in-string/README.md`: Detailed explanation and approach
The solution uses a right-to-left scan to find the rightmost odd digit, leveraging the fact that a number is odd if and only if its last digit is odd. This ensures we get the largest possible odd number as we keep the maximum possible prefix of the original number.
The solution has been tested on LeetCode and passes all test cases.
- Added detailed problem description
- Included multiple examples
- Explained time and space complexity
- Provided clear algorithm explanation
- …

Add solution for Problem #1903: Largest Odd Number in String

---

1903-largest-odd-number-in-string/README.md
1903-largest-odd-number-in-string/largest-odd-number.cpp
2264-largest-3-same-digit-number/README.md
2264-largest-3-same-digit-number/largest-3-same-digit.cpp

Added solution and documentation for LeetCode problem #2264 - Largest 3-Same-Digit Number in String.
- Language: C++
- Time Complexity: O(n)
- Space Complexity: O(1)
- `2264-largest-3-same-digit-number/largest-3-same-digit.cpp`: Implementation
- `2264-largest-3-same-digit-number/README.md`: Detailed explanation and approach
The solution uses a sliding window approach to find substrings of length 3 containing identical digits. It maintains a track of the largest such digit found and returns a string with three occurrences of it.
The solution has been tested on LeetCode and passes all test cases.
- Added comprehensive problem description
- Included multiple examples with explanations
- Explained time and space complexity
- Provided detailed algorithm explanation
- Added implementation …

Add solution for Problem #2264: Largest 3 same digit number in string

---

322_Coin_Change/217-contains-duplicate/README.md
322_Coin_Change/217-contains-duplicate/contains-duplicate.cpp

📄 Summary
This PR adds the Contains Duplicate problem solution to the LeetCode Solutions repository.
It includes a complete implementation in C++, along with a detailed README.md explaining the problem, approach, examples, and complexity analysis.
📚 Details
Problem Link: https://leetcode.com/problems/contains-duplicate/
Approach: Use an unordered_set to track seen numbers. If a number repeats, return true; otherwise, return false.
Files Added:
contains-duplicate.cpp
README.md
⚙️ Complexity
Time Complexity: O(n)
Space Complexity: O(n)
✅ Checklist
Added problem statement and explanation in README
Included well-commented C++ solution
Verified correctness with test cases
Followed repository folder and file structure
🚀 Summary
Added a well-documented and optimized solution for the Contains …

Add solution for LeetCode 217: Contains Duplicate (C++ with README)

---

3005-Count-Elements-With-Maximum-Frequency/Count-Elements-With-Maximum-Frequency.py
3005-Count-Elements-With-Maximum-Frequency/Readme.md

<h2><a href="https://leetcode.com/problems/count-elements-with-maximum-frequency">3005. Count Elements With Maximum Frequency</a></h2>
<hr>
<p>Given an integer array <code>nums</code>, return the <strong>total number of elements</strong> that appear the <strong>maximum number of times</strong>.</p>
<hr>
<p><strong class="example">Example 1:</strong></p>
<div class="example-block">
<p><strong>Input:</strong> <span class="example-io">nums = [1,2,2,3,1,4]</span></p>
<p><strong>Output:</strong> <span class="example-io">4</span></p>
<p><strong>Explanation:</strong></p>
<p>The elements <code>1</code> and <code>2</code> both appear twice, which is the maximum frequency.<br>
Total count = 2 (from 1s) + 2 (from 2s) = 4.</p>
</div>
<p><strong class="example">Example 2:</strong></p>
<div …

Add Solution for Problem#3005: Count Elements With Maximum Frequency
